on: 
  push:
  pull_request:
    types: [opened]
jobs:
  setup-env:
    uses : SOLAIS-FORECAST/devops-workflows/.github/workflows/setup-env.yaml@main
  build-test:
    uses : SOLAIS-FORECAST/devops-workflows/.github/workflows/build.docker-package-python.yaml@main
    needs : setup-env
    with:
      env: ${{ needs.setup-env.outputs.env }}
      aws_account: ${{ needs.setup-env.outputs.aws_account }}
      image_name: api-python-client
      deliver_docker_image: false
  release:
    uses : SOLAIS-FORECAST/devops-workflows/.github/workflows/public-release.yaml@main
    needs : [build-test, setup-env]
    with:
      env: ${{ needs.setup-env.outputs.env }}
    